export const REQUEST_LOGIN   = 'A_REQUEST_LOGIN';
export const REQUEST_ALERTS  = 'A_REQUEST_ALERTS';

export const REQUEST_ALERTS_MOCK = "MA_REQUEST_ALERTS";

export const REQUEST_ALERTS_SUMMARY  = 'A_REQUEST_ALERTS_SUMMARY';